### ISSUE TITLE
`skm ls` need decribe

### ISSUE THREAD

**Issue by lndj** [TimothyYe/skm#12]
the name usually is short, so needs a desc

**Comment by TimothyYe** [comment]
Hi @lndj, what kind of description do you need?

**Comment by lndj** [comment]
For now, the `ls` like this:

```
  ✔ Found 2 SSH key(s)!

->	default
	google-cloud
```

Maybe we need:

```
  ✔ Found 2 SSH key(s)!

->	default                   The default xxxxx
	google-cloud              For google cloud platform...xxx
```

**Comment by TimothyYe** [comment]
@lndj I understand, I'm thinking about where to store these description messages.

**Comment by lndj** [comment]
A file in `~/.skm` ?

**Comment by TimothyYe** [comment]
I'll try it.

**Comment by ebastos** [comment]
You can add comments to [the key itself](https://serverfault.com/questions/442933/add-comment-to-existing-ssh-public-key).

**Comment by TimothyYe** [comment]
This issue is fixed by @ebastos, thanks a lot!
