### ISSUE TITLE
name clash skm is an older ssh key manager too

### ISSUE THREAD

**Issue by michael-paddle** [TimothyYe/skm#13]
Hi Timothy

There is another older SSH Key manager which uses the name skm

  https://sites.google.com/site/jeromeboismartel/code-s-corner/ssh-key-management-with-skimp

I wonder if it wouldn't be better to rename your project so it doesn't clash.  Even sskm or mks or something similar?

  Michael

**Comment by TimothyYe** [comment]
Wow! That's embarrassing!
I take a look at that project, a LAMP project, and manages SSH keys via B/S mode.
Theoretically, that SKM is different from this SKM despite they have the same name.

And for a CLI program, skm is short and efficient for typing, it's a perfect name.

If I decide to rename this project, I need some time to pick up a new name which is suitable for this project and efficient for typing...

**Comment by michael-paddle** [comment]
I wouldn't be embarrassed;  there's even another skm project on GitHub (written in Ruby - it also manages SSH keys ;-) ).  I thought of ksm (matches Same Page Merging - http://searchservervirtualization.techtarget.com/definition/KSM-kernel-samepage-merging but not a program) ssm (matches https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/ch-ssm) and a few others. 

Maybe it's enough to rename the project but keep the binary name?  (Secure Key Multichooser)
