### ISSUE TITLE
无法自定义--store-path

### ISSUE THREAD

**Issue by buyaofangqizhiliao** [TimothyYe/skm#25]
## skm init时指定非默认--store-path不生效

**1.我的环境**
![image](https://user-images.githubusercontent.com/16574870/48995213-f6e3ce80-f181-11e8-8d90-693e83daea7e.png)
**2.操作过程**
   2.1 删除/root/.skm
   2.2 已确认--store-path不存在
![image](https://user-images.githubusercontent.com/16574870/48995326-5215c100-f182-11e8-8272-20a0d7760459.png)
**3.默认--store-path正常**
![image](https://user-images.githubusercontent.com/16574870/48995358-77a2ca80-f182-11e8-84f5-d57aa479edd8.png)
**4.已确认使用centos出现同样问题**
**5.简单看了下main.go，没看出来......**
![image](https://user-images.githubusercontent.com/16574870/48995442-d7997100-f182-11e8-98cf-4cab977105d7.png)

是我打开方式不对吗

**Comment by TimothyYe** [comment]
store-path 应该是一个全局参数，初始化的时候用来指定自定义key store位置。

初始化完成过后，其他命令，也需要带上这个参数，所以你的demo应该改成：

```
skm --store-path "/data/testskm" ls
```

**Comment by TimothyYe** [comment]
当然，这样每次输入都要带上这个参数，用起来也许很不方便，我考虑一下初始化过后如何把这个自定义store path保存下来，方便其他命令直接读取。

**Comment by TimothyYe** [comment]
这个可以作为下一个版本的改进

**Comment by buyaofangqizhiliao** [comment]
> store-path 应该是一个全局参数，初始化的时候用来指定自定义key store位置。
> 
> 初始化完成过后，其他命令，也需要带上这个参数，所以你的demo应该改成：
> 
> ```
> skm --store-path "/data/testskm" ls
> ```

可以了，多谢大佬

**Comment by TimothyYe** [comment]
@buyaofangqizhiliao V0.8  发布了，可以通过导出环境变量的方式自定义store path
https://github.com/TimothyYe/skm/releases/tag/V0.8

用法参考: https://github.com/TimothyYe/skm#customized-ssh-key-store-path
