### ISSUE TITLE
How import existing ssh key?

### ISSUE THREAD

**Issue by TheYkk** [TimothyYe/skm#28]
i have 3 ssh key in ~/.ssh folder  and i use `skm init` is only import default key `id_rsa`

how import all ssh key or how import existing ssh key?

**Comment by TimothyYe** [comment]
You can create directories in ~/.skm
The names of the directory are key alias names, then put your key pair in each directory, and use `skm ls` to list them.

**Comment by TheYkk** [comment]
I already did it, but an easier method must be created

**Comment by TimothyYe** [comment]
For the current design, SKM only imports existing ssh key with supported key types: https://github.com/TimothyYe/skm/blob/master/keytypes.go#L21
