### ISSUE TITLE
Hardcoded version

### ISSUE THREAD

**Issue by katoquro** [TimothyYe/skm#30]
Hello! 

There is hardcoded version in help menu. It always shows 0.5 and confuses after updated.

https://github.com/TimothyYe/skm/blob/f263af35fa2f84734419abdf9730c2627431b19b/cmd/skm/logo.go#L9

**Comment by TimothyYe** [comment]
@katoquro Hello!

Actually, that `0.5` is the default value for the version.
Did you compile `skm` by your self?
There is one `Makefile` https://github.com/TimothyYe/skm/blob/master/cmd/skm/Makefile
Every time when you compile it, you can set the version by yourself, that default value `0.5` will be overwritten:

```
VERSION=0.8.1 make build
```

**Comment by katoquro** [comment]
I've installed via go get: ` go get github.com/TimothyYe/skm/cmd/skm`
and now I have next behavior: 

![image](https://user-images.githubusercontent.com/1694937/99877032-53acdf00-2c0c-11eb-868b-87ca755afbba.png)

**Comment by TimothyYe** [comment]
Hmmmm I see, you install it via `go get`, it might cause the version problem.

I think it is better to install via :

```
brew tap timothyye/tap
brew install timothyye/tap/skm
```

And thanks for your feedback, I'll update the hardcoded version later.

**Comment by katoquro** [comment]
I prefer do not use brew on linux machines so I use `go get`. First time I thought `go get -u` is broken :smile:

**Comment by TimothyYe** [comment]
I've updated the code with the correct version, you may try it again :-)
