### ISSUE TITLE
"display" use a relative path to default ssh path

### ISSUE THREAD

**Issue by frozenkp** [TimothyYe/skm#32]
As title, when use "display" command, skm uses a relative path from default ssh path.
It shows an error like:
```
 % skm dp
Failed to read  ../.skm/github/id_rsa.pub
```

**Comment by TimothyYe** [comment]
Hi @frozenkp, would you pls show me how to reproduce this issue?
I tried from my local machine with the latest version of SKM, it works without any issues.

**Comment by frozenkp** [comment]
Hi,
I tested it on ubuntu 18.04.
I found that when "use" a key, it update the symbolic link in `.ssh` to a relative path of the key. (utils.go:180). When I use "display" command, it retrieves the links in `.ssh` folder and read it directly. (utils.go:263, actions.go:460)

![image](https://user-images.githubusercontent.com/17706351/116709205-06c30500-aa03-11eb-8149-fb6ee63c4a52.png)

**Comment by frozenkp** [comment]
Hi, I tried it on latest golang docker container and get the same problem.
https://asciinema.org/a/VSTRx2050KqnRq3KTNwcjH7CY

**Comment by TimothyYe** [comment]
Thanks, I've already merged your changes, pls use the latest version v0.8.3
