### ISSUE TITLE
SSL certificate is expired.

### ISSUE THREAD

**Issue by kevinchow** [TimothyYe/skm#49]
==> Downloading https://download.xiaozhou.xyz/skm-mac64-0.8.6.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: skm: Failed to download resource "skm"
Download failed: https://download.xiaozhou.xyz/skm-mac64-0.8.6.tar.gz

**Comment by TimothyYe** [comment]
Thanks, it has been fixed.

**Comment by ypo777** [comment]
```
==> Downloading https://download.xiaozhou.xyz/skm-mac-arm64-0.8.6.tar.gz
curl: (60) SSL certificate problem: certificate has expired                                                                                                                       
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: skm: Failed to download resource "skm"
Download failed: https://download.xiaozhou.xyz/skm-mac-arm64-0.8.6.tar.gz
```

SSL is expired again.

**Comment by TimothyYe** [comment]
@ypo777 fixed
