### ISSUE TITLE
Empty skm directory causing skm init to fail

### ISSUE THREAD

**Issue by lsjurczak** [TimothyYe/skm#5]
Hello,

thank you for this SSH key manager. It's really problematic to manage more than one key without it.

I found an issue when I had empty .skm directory. 
`skm init` says `SSH key store initialized!` and it won't copy the SSH keys to the .skm directory.

I have a working fix and I would like to create a PR if you don't mind.

**Comment by TimothyYe** [comment]
@lsjurczak 

Thanks lsjurczak, PR is welcome!
Please create your PR then I can review & merge it.
